### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by srnyx** [Dart2112/AFKPlusPAPI#5]
Purpur 1.17.1
AFkPlusPAPI v1.0.0
https://paste.srnyx.xyz/abumurosav.properties

**Comment by Dart2112** [comment]
I'm sorry, but notifications for this repo seem to be off.
Which means I have missed years of issues posted here. I've rectified the issue so that I should be assigned to issues from now on and am currently handling the backlog.

The most recent update (about to roll out) should fix this as I didnt receive such an error in testing it. Ping me a message on discord if this is still an issue.
